### ISSUE TITLE
Strange directory name in path on GDrive

### ISSUE THREAD

**Issue by papajohn** [data-8/nbgdrive#1]
When I synced from datahub.berkeley.edu with one notebook called `Test Sync.ipynb`, I ended up with the following path in my GDrive, which is weird for two reasons:

`/ > data8/denero > jovyan > Test Sync.ipynb`

- There's a directory called `data8/denero`, which is *not* a two-layer path, but instead a path with a slash in it.
- There's a subdirectory called `jovyan` that appeared out of nowhere.

**Comment by micahcarroll** [comment]
@papajohn
You're right, right now the sync creates a file named `data8/denero`

What format do you think would be best?
- Having an actual two-layer path (a folder `data8` containing a subfolder `denero`)
- Changing the name to something less confusing like `data8-denero`

The advantage of the second way is that it does not create an additional (potentially unnecessary) layer in the folder structure

**Comment by jiefugong** [comment]
This should be fixed -- the user now gets to input what they would like their directory to be named.
