### ISSUE TITLE
Syncs a duplicate into gdrive every time you navigate somewhere in the tree

### ISSUE THREAD

**Issue by SaladRaider** [data-8/nbgdrive#24]
Every time you navigate to somewhere in a tree directory, nbgdrive syncs a duplicate copy of the dir structure to gdrive. It should only update the existing one.

**Comment by jiefugong** [comment]
Is this still an issue @SaladRaider or can it be closed?

**Comment by SaladRaider** [comment]
@jiefugong this is fixed with the recently merged in PR's. yup, I'll close it. Thank you for the reminder.
